services:
  - type: web
    name: gymudec
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    preDeployCommand: php artisan migrate --force
    envVars:
      - key: APP_NAME
        value: GymUDEC
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: gymudec-db
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: gymudec-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: gymudec-db
    plan: free
    databaseName: gymudec
    user: gymudec
